---
- hosts: localhost
  connection: local
  gather_facts: no
#  vars_prompt:
#  - name: secret
#    prompt: Enter secret for key?
  tasks:
  - name: Get Key Vault by name
    azure_rm_keyvault_info:
      resource_group: "{{ RESOURCE_GROUP }}"
      name: "{{ VAULT_NAME }}"
    register: keyvault

  - name: set KeyVault uri fact
    set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"
  - name: set adminPassword
    set_fact: secret=$ec321Pass

  - name: Create a secret
    azure_rm_keyvaultsecret:
      secret_name: Admin-PreProd-ABC-Logistics
      secret_value: "{{secret}}"
      keyvault_uri: "{{ keyvaulturi }}"
