---
- hosts: localhost
  connection: local
#  roles:
    #-  { role: azure.azure_preview_modules }
  vars:

    url: "https://{{VAULT_NAME}}.vault.azure.net/"
    secretname: "{{SECRET_NAME}}"
    client_id: "{{OBJECT_ID}}"
    secret: "{{CLIENT_SECRET}}"
    tenant: "{{TENANT_ID}}"
  tasks:
  - name: Include AZ Preview
    include_role:
      name: azure.azure_preview_modules
    vars:
        skip_azure_sdk: false
  - name: Get Key Vault by name
    azure_rm_keyvault_info:
      resource_group: "{{RESOURCE_GROUP}}"
      name: "{{ VAULT_NAME }}"
    register: keyvault
  - name: Debug
    debug:
      msg="the value of this secret is {{lookup('azure_keyvault_secret',secretname,vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant)}}"


  # - name: Set key vault URI fact
  #   set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  #- name: Set key vault secret fact
  #  set_fact: secretValue={{ lookup('azure_keyvault_secret',secret_name,vault_url=keyvaulturi, client_id=OBJECT_ID, secret=CLIENT_SECRET, tenant_id=TENANT_ID1) }}

  # - name: Output key vault secret
  #   debug:
  #     msg: "{{ secretValue }}"
